---
sudo: false

language: go

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

script:
  - go test $(go list ./... | grep -v /vendor) -cover
